### ISSUE TITLE
You are the best

### ISSUE THREAD

**Issue by steima** [klimeryk/recalendar.js#1]
I have literally just started working on a similar thing a few weeks ago.

I wanted to use your ReCalendar tool as a basis. I am already working on a fork which supports JSON configuration files. Then I wanted to hack together a React / TypeScript frontend which can generate a JSON config, pushes this to a minimal API which just takes each configuration file, generates the calendar from it and mails the user a link to the PDF download.

I don't know for you. But on my home-lab server generating a calendar takes around 30 seconds.

**Comment by klimeryk** [comment]
Hi, @steima! Thanks for the kind words. Kudos on finding this repository :D I have a working version of the code, I'm hoping to be able to launch it this week.

I've taken a bit different approach than in the PHP version. As you mention, the performance is a bit of a problem. I've also run into limitations of the PDF library I chose there. Surprisingly, one of the things I found the most limiting is that the whole layout had to be done via tables (ah, 2000s web design!). The biggest implication of that is the links could not be blocks - you can see why that's an issue in the mini calendar. It's very hard to tap on `1`, for example, because the link only spans the `1` letter - not the whole cell.

Anyway, all that combined, for recalendar.js I opted for a different approach. I re-wrote it in React, using [react-pdf](https://github.com/diegomura/react-pdf) as the library to generate PDFs _on the client-side_. So, no need for a beefy server to be able to handle X users trying to generate PDFs, >30 seconds or more each 😅 The library also uses yogalayout.com, which is based on flexbox and much more, well, flexible 😅 

Of course, it's not without issues. I've solved UI freeze by moving the work to a web worker. But Firefox still is choking on handling the full PDF - for reasons that are eluding me so far. But Chrome and Safari are handling it well, so it seems it's something with Firefox (which pains me, because 1) Firefox is my main browser 2) I hate when stuff doesn't work reliably in all browsers.

But it's a tool that someone will use once a year, so maybe it's a fair price to pay. Especially since it means no data is sent to the server - privacy win!

Anyway, I hope to push all the work so far this week to the repo. As the PHP version, it will be all open-source. So if you want to work on it, I'd definitely be happy to see PRs from you :)

**Comment by steima** [comment]
Cool cool cool ;) I will then definitely take a halt on my approach and wait for your first version. I was thinking now is the perfect time of the year to create a UI for that.

As you mention it is a once-a-year thing. For the computer savy it is a now brainer to come up with a nice version. But even for me, I for instance do not use the retrospective and week planning at all. So it turns out I could actually get away with just the day sheets. It is a bit of fiddling around until I reach the desired result.

Perhaps we can move two of my ideas over to your code base. Of course I am willing to work on them myself:

 - **Make configurations save- and shareable**: So as a user I click together a configuration and can save it. Basically storing the JSON configuration as a file somewhere and changing the users browser URL to `{{baseUrl}}/r/{{hashOfTheConfiguration}}`. This way I can configure a calendar until I am happy, then when my co-worker sees my version (and that's whats definitely happening again) they also want it but with (idk 1-2 small changes). I can send them the link and they adjust their version from there. Further, I can just bookmark the version and continue tweaking from there. Even if this is then just a thing to be used again next year.
 - **Cache of generated PDFs**: Once configuration saving is a thing, of course it would also make sense to cache the PDF somewhere with the same hash as the configuration. So let's say I share the link to my calendar version in a user-group, for others who just want to use the version provided, they can just download the cached PDF.

**Comment by klimeryk** [comment]
> I was thinking now is the perfect time of the year to create a UI for that.

Yup, agreed - it's definitely one of my biggest drives right now to launch it ASAP. I already saw a small uptick of issues and general interest in the PHP/previous version of this script.

> But even for me, I for instance do not use the retrospective and week planning at all. So it turns out I could actually get away with just the day sheets. It is a bit of fiddling around until I reach the desired result.

Absolutely agree. It's something I already implemented in the JS version 👍 Including fallbacks so that linking still works. For example, if you disable the week overview page, clicking on the week number will take you to the first day of the week for it.

> Make configurations save- and shareable

Agreed - it's definitely something I want to have, but probably not for the very first public version. I'm internally already basically saving it as a JSON, so it should not be too hard. "Shareable" part might be trickier - I want to avoid saving any data on any servers. So, I'd have to maybe encode it somehow and put it in the URL? (that you can bookmark, share, etc.). Or show a JSON blob that you can copy and paste somewhere safe, share, etc. But, as with these things, I'd want to make sure I'm not opening myself (and the users) to some nasty attacks :)

> Cache of generated PDFs

This one will probably not be possible to do. Which I'd say is a feature, not a bug ;) If you can easily share a link with your configuration, that'd be ideal. But either way, I don't want to store any data on my server (performance, privacy, additional complexity). Re-generating the PDF should take a minute or two (and a preview takes a few seconds). So it should be a fair trade-off.

**Comment by klimeryk** [comment]
FYI, I've pushed the current version of the code to `master` - there's still quite a few missing pieces, incomplete translations, etc. But what's there should give you the idea of what I'm aiming for with this version.

**Comment by steima** [comment]
Cool will take a look over the weekend, perhaps there are things I can help with.

**Comment by klimeryk** [comment]
Marking this "issue" as closed :) The shareable aspect has been implemented. You simply can upload the same PDF you generated using recalendar.me and the configuration will be automagically reloaded from it :)

Technical details: I was looking for a solution that will avoid storing any data on mine or especially anyone else's servers. But it's technically not feasible to also embed the whole configuration as a GET parameter. Downloading a separate JSON file or copying some strings is also not an user-friendly option.

But then I realized that everyone already does download a file - the PDF. And it's a versatile format that allow file attachments in it. So that's what I did - I embedded a `config.json` in it. If your reader supports it, you can extract it from your calendar. It's just stringified JSON. I added an explicit version to the config file, in case I introduce breaking changes in the future. So that you'll be always able to import your PDF, no matter when you generated it.

And if you wan to share your configuration, you simply send them your PDF (which I guess you already did to show them the calendar).

Naturally, in the spirit of "everything done client-side", the PDF parsing is done on the client only.

**Comment by steima** [comment]
I already tried that and it works great!
