### ISSUE TITLE
Add support for reMarkable Paper Pro

### ISSUE THREAD

**Issue by ovidiusoft** [klimeryk/recalendar.js#123]
Just launched -- https://remarkable.com/store/remarkable-paper/pro 

It looks like the resolution is 2160 x 1620 and also supports colours. The sidebar most likely resembles the one on rM2, so probably size can be calculated based on the higher resolution/DPI vs display size (it's a little larger).

I am considering ordering one, and if I do I will be able to do testing on it if you want to add support in recalendar.

**Comment by brianjdoherty** [comment]
I've got a Pro arriving this week.  I'm also willing to test recalendar on my new device.  Hope you'll add support for the Pro device - your calendar has worked well for me on my rM2 for the last few years.

**Comment by Blerkselmans** [comment]
+1
Used the ReCalendar for 2 years on RM2 (thank you!!), would love to make use in 2025 of larger screen and colours on my new RM Pro!

**Comment by Subersson** [comment]
Love this for my Socialwork Assessment workflow / diary - I'm sure it'll work fine on the rMPP as it is, working well on my A4 Fujitsu Quaderno, but a tailored option for the rMPP would make me a very happy bunny :) Thank you

**Comment by brianjdoherty** [comment]
I've got the Paper Pro now, and the existing calendar PDF actually works fine.  I guess the device is stretching it?  Of course it'd be nice if it was optimized for the screen pixels, but for me it does get the job done the way it is.

**Comment by Blerkselmans** [comment]
> I've got the Paper Pro now, and the existing calendar PDF actually works fine. I guess the device is stretching it? Of course it'd be nice if it was optimized for the screen pixels, but for me it does get the job done the way it is.

I have the RMPP as well, and yes, recalendar works and I am using it daily. It looks like the pdf is indeed using the fiull screen (stretched), I haven't got the RM2 and RMPP side by side to compare). So it still looks good, but it also means there could be more content on each page in the original (non-stretched) size.
And I would like to make use of the different colours when customizing my 2025 calendar.

**Comment by klimeryk** [comment]
Sorry for the slow follow-up here, I'm on it 🫡 

Unfortunately, I don't have a Paper Pro (unless someone wants to donate one 😏), but [based on specifications](https://remarkable.com/store/remarkable-paper/pro/details/features), this PDF should be optimized for Paper Pro and look crisp, fill out the whole width, etc.
[recalendar-pro.pdf](https://github.com/user-attachments/files/17530541/recalendar-pro.pdf)

Could someone confirm that's the case? 🙏

**Comment by klimeryk** [comment]
> +1 for RMPro resolution and color option f.e. for holidays and events :)
> And I would like to make use of the different colours when customizing my 2025 calendar.

I've moved that to a separate issue: https://github.com/klimeryk/recalendar.js/issues/129. Please add your suggestions there 🙇 The more detail, the better!

**Comment by brianjdoherty** [comment]
I've got the Pro now and I just put the recalendar PDF on it.  It looks great - fills the screen (including leaving a gap for the left-side tools as requested), looks sharp (including when I zoomed in, which I'd never do in real usage) and page swipes happen quickly with minimal ghosting.  I'm pleased with the swipe behavior, because I've experienced some issues on the both the rM2 and the Pro with sluggish page turns in very large PDF files.  So, the recalendar seems just fine to me on the Pro!

**Comment by Ayoubb94** [comment]
> Sorry for the slow follow-up here, I'm on it 🫡
> 
> Unfortunately, I don't have a Paper Pro (unless someone wants to donate one 😏), but [based on specifications](https://remarkable.com/store/remarkable-paper/pro/details/features), this PDF should be optimized for Paper Pro and look crisp, fill out the whole width, etc. [recalendar-pro.pdf](https://github.com/user-attachments/files/17530541/recalendar-pro.pdf)
> 
> Could someone confirm that's the case? 🙏

Echoing the above reply - this looks great on the RMPP! I personally prefer line spacing to be a little narrower, but not sure if it’s easy to add that as a customisable option - small lined, medium lined, and large lined?

But otherwise it fits well, the shading is showing well on the RMPP screen, and the resolution is great.
This particular test pdf though doesn’t leave a gap for the left-side tools (except on the full year view), but I assume that will be an option just as it is in the current version?

Thanks a lot once again for investing your time in this! :)

**Comment by klimeryk** [comment]
Thanks for verifying! I've pushed https://github.com/klimeryk/recalendar.js/commit/4935063698c457f574d96695851b4ff0cd6691bf that adds a new option: Device.

<img width="707" alt="Screenshot 2024-10-26 at 22 06 45" src="https://github.com/user-attachments/assets/8f235e40-7d8a-4c0c-951e-86e4fdad69bc">

It automatically sets the full/optimal resolution and DPI for ReMarkable devices.
While I was at it, I also added a Custom option so that folks can tweak this (and use for other devices than ReMarkable):
<img width="708" alt="Screenshot 2024-10-26 at 22 07 48" src="https://github.com/user-attachments/assets/bd6e9f65-2f6b-4ad3-8351-16941692b921">

Hopefully this fixes this issue and I did not introduce new bugs in the process ;) Please do let me know if you notice anything off. It's possible that the Paper Pro support requires additional tweaking - I'm thinking especially about the space for the toolbar. It's hardcoded to the width of the toolbar on ReMarkable 1/2, but it might be a different width on Paper Pro. Please let me know if the size is not correct 🙇

**Comment by Ayoubb94** [comment]
> Thanks for verifying! I've pushed [4935063](https://github.com/klimeryk/recalendar.js/commit/4935063698c457f574d96695851b4ff0cd6691bf) that adds a new option: Device.
> 
> <img alt="Screenshot 2024-10-26 at 22 06 45" width="707" src="https://private-user-images.githubusercontent.com/3392497/380455399-8f235e40-7d8a-4c0c-951e-86e4fdad69bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTcyNzEsIm5iZiI6MTczMDA1Njk3MSwicGF0aCI6Ii8zMzkyNDk3LzM4MDQ1NTM5OS04ZjIzNWU0MC03ZDhhLTRjMGMtOTUxZS04NmU0ZmRhZDY5YmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjdUMTkyMjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzU4ODhlMjI4YjU0MWI3MjYzMzBiODFkN2MwOTgzZDEyNDhkY2ZlOTI3ZTU4NmI4ZTI1MDk5ZWQyZTgzZjdjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cwknFMs1T4-kp9P9V-Voz9wQq-RQ_kWuef_vcHKfGMM">
> It automatically sets the full/optimal resolution and DPI for ReMarkable devices. While I was at it, I also added a Custom option so that folks can tweak this (and use for other devices than ReMarkable): <img alt="Screenshot 2024-10-26 at 22 07 48" width="708" src="https://private-user-images.githubusercontent.com/3392497/380455437-bd6e9f65-2f6b-4ad3-8351-16941692b921.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwNTcyNzEsIm5iZiI6MTczMDA1Njk3MSwicGF0aCI6Ii8zMzkyNDk3LzM4MDQ1NTQzNy1iZDZlOWY2NS0yZjZiLTRhZDMtODM1MS0xNjk0MTY5MmI5MjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjdUMTkyMjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2Q1MTk4MjRhNjA4NzlhMTI5ZjZjZmUxOTRhZTYyZWZhODM1MDZlMWIxNWQ5YjE2ZGI0MDYwYWY3YmRkYzkwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.bsfjsdwRsUKo5FKhWOCoom082zrsch7MXaZqpGrs-7Q">
> 
> Hopefully this fixes this issue and I did not introduce new bugs in the process ;) Please do let me know if you notice anything off. It's possible that the Paper Pro support requires additional tweaking - I'm thinking especially about the space for the toolbar. It's hardcoded to the width of the toolbar on ReMarkable 1/2, but it might be a different width on Paper Pro. Please let me know if the size is not correct 🙇

Thank you so much for pushing this - it looks great! Not encountered any bugs. The Left toolbar just ever so slightly covers the page. Maybe 1mm or so.

**Comment by Subersson** [comment]
Thank you :)
