### ISSUE TITLE
Production version in website is not applying correctly the pt-BR locale

### ISSUE THREAD

**Issue by carlosvsilva** [klimeryk/recalendar.js#124]
Hi thanks for this amazing project, could really turbocharge my eReader (Boox Note 2 10" btw)

The only issue I run into, is the portuguese string in pdf.json is not being applied to the portuguese Basic calendar, regarding the translation for _week_ (semana).

Could you please fix the public version, using the already existing translation in pdf.json, or better yet, fix the portuguese written in that JSON, which should read:
instead of `retrospetiva para semana`
it should be corrected to `retrospeCtiva DA semana`

Can you please patch this in? Thanks a lot!

Cheers,
Carlos

**Comment by klimeryk** [comment]
Thanks for reporting! Looks like there was an issue detecting properly the `pt-BR` locale - sorry about that! It should be fixed in https://github.com/klimeryk/recalendar.js/commit/8843471879ef9b55ef1266940e711628126466b6. Could you try again and let me know if it's working as expected now for you? 🙏
