### ISSUE TITLE
Special Dates Limitations and error?

### ISSUE THREAD

**Issue by raybruce93** [klimeryk/recalendar.js#29]
Are there limitations to how many special days/events I can add to the calendar? I am adding birthdays, special occasions, U.S. holidays, and church calendar holidays to the calendar and each time I hit preview, I get an error, and all my customizations reset and are lost. Every time. 54 dates in all. @klimeryk 

I thought adding dates a few at a time, then refreshing might work. It didn't. The one thing I haven't tried is adding dates, generating in full, then reuploading the previously generated file and adding more, etc.

I am using Google Chrome on Windows 10.
![ReCalendar Error](https://user-images.githubusercontent.com/102770440/161172310-cc561e25-352a-4b36-8f4b-c47177c21d87.jpg)

**Comment by raybruce93** [comment]
UPDATE: I was eventually able to add all 54 special events/holidays/occasions, but I did it in batches, generating and downloading after each batch, then re-uploading from the last saved version, and adding more dates each time. Thankfully, I only have to do this once, as my re-upload for next year will have everything I need now.

Thanks for this wonderful free tool. I will let you close this in case you deem this an action item for future tweaks.


> Are there limitations to how many special days/events I can add to the calendar? I am adding birthdays, special occasions, U.S. holidays, and church calendar holidays to the calendar and each time I hit preview, I get an error, and all my customizations reset and are lost. Every time. 54 dates in all. @klimeryk
> 
> I thought adding dates a few at a time, then refreshing might work. It didn't. The one thing I haven't tried is adding dates, generating in full, then reuploading the previously generated file and adding more, etc.
> 
> I am using Google Chrome on Windows 10. ![ReCalendar Error](https://user-images.githubusercontent.com/102770440/161172310-cc561e25-352a-4b36-8f4b-c47177c21d87.jpg)

**Comment by klimeryk** [comment]
Hi, @raybruce93! Thanks for testing it out and pushing ReCalendar to its limits! Sorry you run into such issues - there should be _no_ limitations on the number of special dates. I've tried replicating your issue, but could not in neither Firefox of Chrome:

<img width="1421" alt="Screenshot 2023-04-17 at 21 53 59" src="https://user-images.githubusercontent.com/3392497/232619452-6e715f4e-5620-4e7a-b614-bb81dd4662b1.png">
<img width="1417" alt="Screenshot 2023-04-17 at 21 54 09" src="https://user-images.githubusercontent.com/3392497/232619461-0c2e5db2-1467-4622-9f19-8440245829b4.png">

I've tried with 20 special dates and did not notice any issues. Looking at the code, I'm also not seeing what could have caused this issue for you. I've done some updates and work since then, so maybe either it has resolved itself or there was something else at play (an extension in your browser conflicting with ReCalendar?).
Anyway, marking as closed, but thanks for reporting! Hope this year you had no issues (re-)adding your special dates!
