### ISSUE TITLE
No links in pdf past week 5 of 2023

### ISSUE THREAD

**Issue by jujulroger** [klimeryk/recalendar.js#35]
Everything seems to work except the pdf contains no links past week 5 of 2023. Tried to change the starting month and noticed the following behavior : 

- Any (?) month before and up to Feb. 2023 breaks links after week 5 2023
- Choosing March 2023 "fixes" the issue.
- The issue comes up again at the start of February 2024

**Comment by dev-ndn** [comment]
As the config is part of the generated pdf, maybe you could provide such a broken pdf or the exact configuration of the problem so it can be reproduced. I actually only had the issue of links only working up to week 5 when I downloaded/used the preview pdf instead of using the button below the preview pdf to generate the full pdf. 🙈

**Comment by jujulroger** [comment]
Welp thanks ! I don't feel so bright right now... Generating the whole file "fixes the issue". I guess since I was seeing the whole calendar despite the warning "only first month is rendered for preview", I thought I could just download it directly from the pdf viewer without generating the whole file. 

Everyting works great, maybe the warning could be changed a bit to make it clearer that the file downloaded from the preview is incomplete ?
