### ISSUE TITLE
Links when pages left out...

### ISSUE THREAD

**Issue by alan412** [klimeryk/recalendar.js#36]
I generate a calendar that has only week overview and retrospective.

What happens now:
* Clicking on the month title or a day of the month takes you nowhere
* Clicking on a day of the month takes you nowhere

What I would like to happen:
* Clicking on a month title would you take you to the week overview that contains the 1st of that month
* Clicking on a day of the month would take you to the week overview that contains that day.

If I think about generalizing it, I would recommend:
* Clicking on a month title
   * If there is a month overview, go there.
   * Else, if there is a week overview go to the one with the 1st of the month
   * Else, go to the 1st day of the month day overview (if it exists)
   * Else, do nothing

* Clicking on a day title
  * If there is a day overview go there
  * Else, if there is a week overview go to the one with that day
  * Else, if there Is a month overview go to the one with that day
  * Else, do nothing

**Comment by klimeryk** [comment]
Hi, @alan412! Thanks for reporting the issue. I did not this about this use case. I had some fallbacks, but they assumed there was at least one day itinerary enabled 😀 
Appreciate the generalized solution you've outlined - I've implemented it mostly as-is. The only adjustment was for the what happens if: clicking on a month title -> month overview disabled. I decided to go with _first_ try the first available day of the month and only if that fails, go for the week overview. Two reasons: one, this is the current behaviour (minus the fallback to week overview). Two, it felt more what I'd expect to happen. Weeks rarely start with the beginning of the month, so it felt like it'd be more helpful to go to the first day of the month instead.

One edge case that came out of this: if month overviews are disabled _and_ day itineraries are disabled, then when week overviews are enabled clicking on a month will go to the week overview that contains the first day of that month, as expected. What's not expected is that the minicalendar (in top right) will usually show the _previous_ month (because the week usually is in the previous month). So the next month link in that minicalendar actually leads... to the same page and does nothing :( I'm not sure how to fix that. Each component is working correctly, but together, in that particular context, it leads to an unexpected/confusing outcome :/

Hope this helps! I _think_ I've covered all the bases, but let me know if you notice anything off 🙇
