### ISSUE TITLE
Translation to Croatian language (Hrvatski jezik)

### ISSUE THREAD

**Issue by bruno-dogancic** [klimeryk/recalendar.js#60]
Dear Igor @klimeryk ,

First of all, many kudos and thanks for such a "simple" (in a sense of simply and elegantly solving a great problem) yet such a great project.

The moment I've seen it I wanted to contribute. Although I do have programming experience, this is literally my first ever encounter with `JAVA/JAVA script,` `node.js` and `yarn/npm` ever, so please bear with me. :sweat_smile: 

I have translated the values in `app.json` , `config.json` and `pdf.json` . I have also tinkered a bit with `pdf/config.json` file to make a PDF suitable for my tablet (Samsung Galaxy Tab S8+). The site loaded without any errors as expected, but here are some of the problems that I have observed.

In the APP itself, the menu for changing language shows twice:

![Screenshot from 2023-02-12 00-56-00](https://user-images.githubusercontent.com/33345676/218286221-fb4fcc8b-c9eb-494d-8a0c-166d56c4e9b0.jpg)

On the other hand, when the APP is in the English language, languages still occur twice, but also the name of the language is `language.hr`:

![Untitled](https://user-images.githubusercontent.com/33345676/218286332-2f4fa195-c2f4-480f-a4e7-14420c8a3457.png)

Without hardcore language proofing (there are still some things I will change in the final version), other things seem to me to render just fine within the APP (website). Not sure if the FAQ and other headers should do anything when clicked in a deployment version, though - but currently nothing happens - on my side. A full screenshot of the APP is below:

![Untitled1](https://user-images.githubusercontent.com/33345676/218286432-cbbd7892-063c-46f2-9697-1b4f46131904.png)

Then, I noticed some of the fonts affects the PDF document rendition. Characters "č" and "đ" are not rendered properly in the PDF document:

![Untitled1](https://user-images.githubusercontent.com/33345676/218286709-eabdb663-6ef3-40a9-a7b7-344e6f3d2e82.png)

From what I was able to check, from the four provided fonts, the Lato doesn't support previously mention Croatian characters. Other three do support.

![rwerqr](https://user-images.githubusercontent.com/33345676/218287730-cbc02f79-0bd8-459f-af0e-1c2398726de5.png)

I have tried to replace Lato with Roboto and indeed it worked. I've done so by editing `fonts.js` to something like this 
```
//export const LATO = 'Lato';
export const LATO = 'Roboto';
```
and also added Roboto to `public/fonts`. This produces expected result.

![bdjbasd](https://user-images.githubusercontent.com/33345676/218287922-bfca731b-2cf5-4e01-a44c-c66171584f0c.png)

**EDIT1:** After a more thorough look at the configuration, I've came to conclusion that there is already a possibility to choose font within the APP. My bad interpretation of `.json` files was that the 4 fonts were used for different things within the documents. :man_facepalming: 

Also, the `pageSize` layout I used for this example (slightly taller and wider than yours) [ '167mm', '256mm' ]; renders the PDF document to have context on the top of the page. Not big of a deal but could perhaps be fixed by centering context vertically on the page or something similar.

![Untitled2](https://user-images.githubusercontent.com/33345676/218286818-3166e8a3-876e-4664-81f9-fd93baaf2eca.png)

From what I've seen, month, week and day pages look rather good.

**EDIT2:** I have also noticed thad right padding is off for Habits as seen on the image below:

![fsdfdssdf](https://user-images.githubusercontent.com/33345676/218335036-c411e7eb-722a-4090-a9f1-99ef57df6e6d.png)

Here is a document it created.
[recalendar.pdf](https://github.com/klimeryk/recalendar.js/files/10715065/recalendar.pdf)

Also roboto version:
[recalendar_roboto.pdf](https://github.com/klimeryk/recalendar.js/files/10715066/recalendar_roboto.pdf)

I will proof and polish (no pun intended) my translations when I get some more time and will upload it afterwards. But for now, the locale as is is also here.
[hr_unpolished.zip](https://github.com/klimeryk/recalendar.js/files/10715087/hr_unpolished.zip)

Besides the things observed, here are the recommendations from my side:

- Add option in the APP to choose layout size. Doesn't seem to be too demanding. I've tested many weird sizes and most of them rendered good, unless the size was too small to show mini calendars. From my testing, any size around the size of a remarkable and larger renders just great. For smaller sizes, perhaps it could be possible to use some scaling? By doing so this great project might reach even larger audience.
- Perhaps use the word schedule (and schedule item) instead of itineraries (and itinerary)? I was so confused at first, since this word automatically associates me on journey (and not time) planning. Perhaps it is just me :rofl: I'm willing to get into the nitty gritty of changing values in locales if need-be.
- Add option to insert image for cover of the calendar/digital notebook. Would be so great to further personalize it! :heart_eyes:  
- I think this project deserves to be highlighted more towards tablets (with pen support?) in general and not only for Remarkable, since I've been looking into something like this for quite some time! :muscle: 

Since I started to get more into `js` and `json` and it doesn't seem to much complex, I might try to implement some of the things said before, but I cannot promise I will be able to do it successfully in the near future. If you can instruct me on how to take a look at logs etc., I'm more than willing to help with testing and in general! Looking forward to hearing back from you. 

Warm regards,
Bruno

**Comment by klimeryk** [comment]
Hi @bruno-dogancic! First of all, thank you for the kinds words. And for jumping in fearlessly into the project! Looks like you found some bugs that made the experience less than smooth. I've been cleaning up some old issues and looks like I fixed them in the meantime:

 - The duplicated languages in the select list: https://github.com/klimeryk/recalendar.js/commit/f107d307d2ed5ada89811fa4317faebc0e3bdae8
 - Missing "č" and "đ" characters - run into the same issue when I tried to add the Czech translations - turns out I was using an older version of the Lato font. The newest one handles these characters without trouble: https://github.com/klimeryk/recalendar.js/commit/b4e5f01d82a1478aadc6c55f17205f256e2ccc4f. Make sure to clear the browser's cache (or using an incognito/private window) to ensure the new font is used.

> Add option in the APP to choose layout size. Doesn't seem to be too demanding. I've tested many weird sizes and most of them rendered good, unless the size was too small to show mini calendars. From my testing, any size around the size of a remarkable and larger renders just great. For smaller sizes, perhaps it could be possible to use some scaling? By doing so this great project might reach even larger audience.

I want to do that (and there's some pending requests about specific devices). The main issue is me not having those devices and not being able to test physically on them. Sometimes that helps uncover some issues - like the fact that ReMarkable has a side toolbar. Or that when it's minimized, it can obstruct things in the top left corner.

Then there's making sure it does not break at arbitrary sizes. From what I remember, it did not always scale nicely, there's a few things that I had to squeeze as much as possible. Though I've tried to keep it responsive. I'll definitely test more.

> Perhaps use the word schedule (and schedule item) instead of itineraries (and itinerary)? I was so confused at first, since this word automatically associates me on journey (and not time) planning. Perhaps it is just me 🤣 I'm willing to get into the nitty gritty of changing values in locales if need-be.

Hah, that might be just me not being a native English speaker 😅 Schedule feels too... scheduled :D Meaning, it's bound to hours. While itinerary is more free-form. You can add hours yourself, but also just put items on the agenda.

> Add option to insert image for cover of the calendar/digital notebook. Would be so great to further personalize it! 😍

I like it! I've added a separate issue to track this feature request: https://github.com/klimeryk/recalendar.js/issues/66.

> I think this project deserves to be highlighted more towards tablets (with pen support?) in general and not only for Remarkable, since I've been looking into something like this for quite some time! 💪

Possibly, but I don't use one, so hard for me to tell how they are used. I'm imagining iPad and folks using keyboard (on screen or physical one) instead of writing with a pen. But might be worth exploring.
