### ISSUE TITLE
"Unable to view" error - on firmware 3.*

### ISSUE THREAD

**Issue by nicolabotta** [klimeryk/recalendar.js#68]
Thanks for providing `recalendar`! 

Since upgrading to Version 3.3.2.1666, opening  `recalendar` on my rM1 yields an _"Unable to view - This document contains data that is not supported"_  error.

The files associated with `recalendar` can be downloaded via `rmapi` with `get recalendar`. However, `geta recalendar` (download the files associated with recalendar and generate a .PDF file) yields

```
[/]>geta recalendar
downloading: [recalendar]...
Error: Failed to generate annotations for recalendar with archive does not contain a unique pagedata file
[/]>exit
```
Any idea how to recover my (re)calendar? 

Thanks, 
Nicola

**Comment by nicolabotta** [comment]
PS: uploading and opening a fresh recalendar works fine, thus perhaps the old calendar was corrupted by the system upgrade.

**Comment by klimeryk** [comment]
Thanks for reporting, @nicolabotta! That's the first I've heard of an issue with the 3.* firmware 🤔 I _hope_ it was a one-off, maybe indeed something got corrupted/changed in the PDF during the upgrade. I'm still on 2.* firmware because I like https://github.com/ddvk/remarkable-hacks and [they don't support 3.* yet](https://github.com/ddvk/remarkable-hacks/issues/496).
I'll keep this issue open for now, in case other folks run into the same issue. But nothing fundamental has changed on the ReCalendar side of things - and what it's generating is a perfectly standard PDF as far as I can tell. So fingers crossed it's just growing pains of the new 3.* firmware 🤞

**Comment by klimeryk** [comment]
Thanks for confirming, @ovidiusoft! Appreciate it - I can close the issue more confidently now 🙇‍♂️
