### ISSUE TITLE
Hyperlinks not working for most of the months/days

### ISSUE THREAD

**Issue by Hitcho84** [klimeryk/recalendar.js#74]
Hi there
Hyperlinks not working for most of the months/days. January is working fine but not so for the other months.

**Comment by klimeryk** [comment]
Could you share more details? Sounds like you might have generated just the preview (which indeed only covers January). There's a button under the preview to generate the full calendar:
<img width="701" alt="Screenshot 2023-05-20 at 17 54 08" src="https://github.com/klimeryk/recalendar.js/assets/3392497/c0aa20c3-7891-432a-b1ec-4b7747faecf7">

Generating the full calendar (for 12 months) is literally 12x longer than the preview (just one month), that's why it's split in two steps. So that you can easily tweak and preview your calendar before comitting to generating the full one. Hope this helps!
