### ISSUE TITLE
The list over special dates is not sorted correctly. 

### ISSUE THREAD

**Issue by moloean** [klimeryk/recalendar.js#88]
The look like the special days is sorted descending by year and ascending by month and day.

I think that the year also should be sorted ascending.

**Comment by klimeryk** [comment]
Could you share an example? I want to make sure I understand the issue correctly. Because behind the scenes, the year part is not taken into account at all. There's a year selector, but that's just provided by the standard "date picker" from the browser. The date part is discarded and [only month and day are used](https://github.com/klimeryk/recalendar.js/blob/f598b4152dbe6e6ad1869bb19313ae9990756963/src/configuration-form/special-dates.jsx#L29).

I can see how in certain cases it could be useful - if the calendar is more than 12 months and in one year there's a special event in that month, but not the next year. But I think that might be getting too much into the edge case territory - even for this highly customizable calendar generator 😅 

For now I'll close the issue, but please do re-open if I misunderstood the issue - in which case please share more details on what exactly you'd like to see 🙇
